MENU = 'mn'

CATEGORIES = 'ctgs'
CATEGORY = 'ctg'
ADD_CATEGORY = 'actg'
CATEGORY_SETTINGS = 'sctg'
EDIT_CATEGORY_NAME = 'enctg'
DELETE_CATEGORY = 'dctg'

ADD_ACTIVITY = 'aact'
ACTIVITY_SETTINGS = 'sact'
EDIT_ACTIVITY_NAME = 'enact'
EDIT_ACTIVITY_CATEGORY = 'ecact'
DELETE_ACTIVITY = 'dact'

STATISTICS = 'sttst'

TRACK = 'trk'

START_TRACKING = 'sttr'
STOP_TRACKING = 'stptr'
